version: "3.8"

services:
  node1:
    build: .
    restart: always
    container_name: node1
    ports:
      - "8080:8080"
    links:
      - node3
      - node2
  node2:
    build: .
    restart: always
    container_name: node2
    ports:
      - "8081:8080"
   
  node3:
    build: .
    restart: always
    container_name: node3
    ports:
      - "8082:8080"
 
  # mongo:
  #   image: mongo
  #   # restart: always
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: root
  #     MONGO_INITDB_ROOT_PASSWORD: example
  #   ports:
  #     - "27017:27017"
  # mongo2:
  #   image: mongo
  #   # restart: always
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: root
  #     MONGO_INITDB_ROOT_PASSWORD: example
  #   ports:
  #     - "27018:27017"
  # mongo3:
  #   image: mongo
  #   # restart: always
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: root
  #     MONGO_INITDB_ROOT_PASSWORD: example
  #   ports:
  #     - "27019:27017"
